name: nonproduction-ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare Lambda Version
      shell: bash
      run: echo "##[set-output name=version;]$(date +%Y%m%d%H%M)"
      id: lambda_version

    - name: Echo Env
      run: |
        echo ${{ steps.lambda_version.outputs.version }}

    - name: Build j5
      run: |
        cd j5
        npm install
        npm prune --production
        zip -qr j5.zip lib node_modules handler.js package.json

    - name: Build log-store
      run: |
        cd log-store
        npm install
        npm prune --production
        zip -qr log-store.zip lib node_modules handler.js package.json

    - name: Configure AWS credentials from DEV account and assume a role for Terraform commands
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.DEV_AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        aws-region: us-east-1

    - name: Deliver to S3 bucket
      run: echo Hello, world!
